meta_product_name: "Kanpai"
meta_title: "Kanpi - It's your time to go outside!"
meta_description: "Relevant description"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@kanpai_twitter_account"   # required for Twitter Cards
