meta_product_name: "Kanpai"
meta_title: "Kanpai - A spot for everyone"
meta_description: "Cool app for finding free spot to drink or to eat"
meta_image: "cover.png" # should exist in `app/assets/images/`